### PR TITLE
Fixed failing travis builds

### PR DESCRIPTION
**Pull request by jecihjoy**

### CODE REVIEW

**Comment by dkayiwa** [comment]
Are all these changes necessary to fix the travis build failure?

**Comment by jecihjoy** [comment]
The JDK that was being installed was missing tools.jar and rt.jar libraries. Switched to openjdk8 which has all the required libraries and it is the standard one being used across openmrs modules

**Comment by dkayiwa** [comment]
I thought just adding `openjdk8` alone should be enough to fix it. Do you need all the other changes?

**Comment by jecihjoy** [comment]
I have reverted the additional changes, check the PR now

**Comment by dkayiwa** [comment]
Is there any reason why you removed lines 3 to 6?

**Comment by dkayiwa** [comment]
@jecihjoy any response to the above?

**Comment by jecihjoy** [comment]
@dkayiwa line 3 to 6 was installing java package manager **jpm** which was then used to install  JDK version in line 5. This JDK is however  missing tools.jar and rt.jar libraries hence causing the travis fail issue.

**Comment by dkayiwa** [comment]
@jecihjoy can we remove those lines to prove that travis will fail?

**Comment by jecihjoy** [comment]
@dkayiwa  Do you mean reverting to what it was then testing it out?

**Comment by dkayiwa** [comment]
@jecihjoy i mean reverting the changes you made to lines 3 up to 6

**Comment by jecihjoy** [comment]
worked like a champ 🎁

**Comment by dkayiwa** [comment]
@jecihjoy so do you now see what i was talking about? 😊

**Comment by jecihjoy** [comment]
I see. I must have misunderstood what line 3 to 6 was doing.
Also @dkayiwa anything else that needs changing here?

**Comment by dkayiwa** [comment]
I guess the merge answers your question. 😊

**Comment by jecihjoy** [comment]
Thanks @dkayiwa

**Pull request merged**
